version: '3.8'

services:
  ai_service:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - qdrant
      - redis
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      # These environment variables allow your app to connect using service names
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  qdrant_storage:
  redis_data:
