version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_service
    restart: always  # Ensures it restarts if it stops
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage  # Persistent storage

volumes:
  qdrant_storage:
